"""TOML manifest adapter — read via stdlib ``tomllib``, write via a small
hand-rolled serializer.

``tomllib`` (Python 3.11+) reads TOML but cannot write it, and we want zero pip
dependencies on a fresh machine. The writer here is deliberately narrow: it
serializes exactly the manifest schema this engine defines, not arbitrary TOML.
Rewriting the file (on add/pin/remove) is lossy for hand-written comments except
the file header, which is re-emitted each time — a documented tradeoff.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

from .domain import KNOWN_PLATFORMS, LATEST, Manifest, Tool
from .ports import ManifestStore

# A TOML bare key is ASCII letters, digits, underscores and dashes; anything
# else (e.g. the @ and . in "node@22", "python@3.13") must be a quoted key.
_BARE_KEY = re.compile(r"^[A-Za-z0-9_-]+$")

_HEADER = """\
# software.toml — the single source of truth for every tool zconfig manages.
#
# Each [tools.<name>] block declares one piece of software. Fields:
#   manager      brew | apt | cargo | npm | pnpm | pipx | go | script | manual
#   package      the package/identifier the manager installs
#   version      "latest" (track upstream) or an exact pin e.g. "14.1.0"
#   platforms    where it applies: any of ["macos", "linux", "wsl"]
#   tags         freeform groups for subset installs e.g. ["core", "dev"]
#   pre_install  / post_install   optional shell hooks (post doubles as a health check)
#
# Per-platform overrides (different package name per OS) go in a sub-table:
#   [tools.fd.overrides.linux]
#   manager = "apt"
#   package = "fd-find"
#
# Adapter-specific extras go under [tools.<name>.options] (e.g. brew cask = true).
#
# This file is regenerated by `zconfig add/pin/remove`; comments below this
# header are not preserved across those commands.
"""


class TomlManifestStore(ManifestStore):
    def __init__(self, path: Path) -> None:
        self.path = path

    def exists(self) -> bool:
        return self.path.exists()

    def load(self) -> Manifest:
        with self.path.open("rb") as handle:
            data = tomllib.load(handle)
        tools_table = data.get("tools", {})
        tools = tuple(_parse_tool(name, body) for name, body in sorted(tools_table.items()))
        return Manifest(tools=tools)

    def save(self, manifest: Manifest) -> None:
        chunks = [_HEADER]
        for tool in sorted(manifest.tools, key=lambda t: t.name):
            chunks.append(_render_tool(tool))
        self.path.write_text("\n".join(chunks).rstrip() + "\n", encoding="utf-8")


def _parse_tool(name: str, body: dict) -> Tool:
    overrides_raw = body.get("overrides", {})
    overrides = {plat: dict(over) for plat, over in overrides_raw.items()}
    return Tool(
        name=name,
        manager=str(body.get("manager", "manual")),
        package=str(body.get("package", name)),
        version=str(body.get("version", LATEST)),
        platforms=tuple(body.get("platforms", KNOWN_PLATFORMS)),
        tags=tuple(body.get("tags", ())),
        pre_install=_opt(body.get("pre_install")),
        post_install=_opt(body.get("post_install")),
        options=dict(body.get("options", {})),
        overrides=overrides,
    )


def _key(name: str) -> str:
    """Render a table/key segment, quoting it when it isn't a bare TOML key."""
    return name if _BARE_KEY.match(name) else _v(name)


def _render_tool(tool: Tool) -> str:
    head = f"tools.{_key(tool.name)}"
    lines = [f"[{head}]"]
    lines.append(f"manager = {_v(tool.manager)}")
    lines.append(f"package = {_v(tool.package)}")
    lines.append(f"version = {_v(tool.version)}")
    if tuple(tool.platforms) != tuple(KNOWN_PLATFORMS):
        lines.append(f"platforms = {_v(list(tool.platforms))}")
    else:
        lines.append(f"platforms = {_v(list(KNOWN_PLATFORMS))}")
    if tool.tags:
        lines.append(f"tags = {_v(list(tool.tags))}")
    if tool.pre_install:
        lines.append(f"pre_install = {_v(tool.pre_install)}")
    if tool.post_install:
        lines.append(f"post_install = {_v(tool.post_install)}")
    block = "\n".join(lines)

    if tool.options:
        block += f"\n\n[{head}.options]\n" + _render_table(tool.options)
    for plat in sorted(tool.overrides):
        over = tool.overrides[plat]
        nested = {k: v for k, v in over.items() if k != "options"}
        if nested:
            block += f"\n\n[{head}.overrides.{_key(plat)}]\n" + _render_table(nested)
        if over.get("options"):
            block += f"\n\n[{head}.overrides.{_key(plat)}.options]\n" + _render_table(over["options"])
    return block + "\n"


def _render_table(table: dict) -> str:
    return "\n".join(f"{_key(key)} = {_v(value)}" for key, value in table.items())


def _v(value: object) -> str:
    """Serialize a scalar/array to a TOML literal. Covers the manifest schema only."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_v(item) for item in value) + "]"
    raise TypeError(f"unserializable manifest value: {value!r}")


def _opt(value) -> str | None:
    return None if value is None else str(value)
